### ISSUE TITLE
Click Area of "Click Me" button does not work on every browser "Samsung Browser"

### ISSUE THREAD

**Issue by Nixkuchengifthub** [code0-tech/pictor#49] opened 2024-02-13 11:52 UTC
When clicking the button by just touching a corner it does light up as beeing clicked but nothing opens in response to the interaction, depending on how far of you are from the center of the visible button.

**Comment by Knerio** [comment] 2024-02-13 11:54
Chrome on Android 13 is working better but the issue is on chrome also there

**Comment by nicosammito** [comment] 2024-02-13 13:55
It could relate to the wrapper that is not working as intended:

```js

<div ref={triggerRef}>
{menuTrigger ? React.cloneElement(menuTrigger.props.children, {...buttonProps, tabIndex: 1}) : null}
</div>

```

**Comment by nicosammito** [comment] 2024-02-13 14:04
It’s a general Issue on all browsers. Trying to move the menuTrigger props to the wrapper. Thus could potentially fix this issue

**Comment by nicosammito** [comment] 2024-02-13 14:43
This is an issue inside of Aria. Hopefully they fix it soon:

https://github.com/adobe/react-spectrum/issues/1061

**Comment by nicosammito** [comment] 2024-03-03 16:50
We can close this for now, because aria will not fix this any soon

**Closed by nicosammito** 2024-03-03 16:50 UTC
Labels: bug
